# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17DR1rNYtFwty6PArK_N8Tz8-RsriGC0c

#Supervised Machine Learning
#Sai kumar Murarishetti
#Week 6: Final Project Part 1


(https:/https://www.kaggle.com/datasets/asishpandey/crop-production-in-india/data/)
"""

# Used for Importing of libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from google.colab import files

# This is used to upload the dataset
df=files.upload()
df = pd.read_csv('Crop_production.csv')

# This is used to display first 10 lines from the dataset
print(df.head(10))

# This is used to Display a summary of DataFrame 'df' for data inspection and understanding.
print(df.info)

#this is used to display rows and colums
df.shape

#This is Generate descriptive statistics for numeric columns in DataFrame.
df.describe()

#This is a square DataFrame where each cell contains the correlation coefficient between two columns
data.corr()

# This is used to create histograms for all the numeric columns
data.hist()